name: trigger

on:
  push:
    branches:
    - master

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: trigger
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TRIGGER_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/gofrp/frp-site/actions/workflows/build.yml/dispatches \
          -d '{"ref":"master"}'
